# SITE SETTINGS
title: Darwin Core Data Package
author: Darwin Core Maintenance Group
url: "https://gbif.github.io"
baseurl: "/dwc-dp"

# SOCIAL PROFILES
social:
  github: gbif/dwc-dp
  email: dwcdp@gbif.org

# THEME SETTINGS (ALL OPTIONAL)
theme: minima
remote_theme: tdwg/petridish
github_edit: true

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
