/*
Title: Darwin Core Data Package PostgreSQL schema
Version: 2026-03-19
Source table schemas: table-schemas/
Generated by: generate_sql.py

Notes:
- Generated from DwC-DP table schemas plus PostgreSQL sidecar configuration.
- foreignKeys are rendered as PostgreSQL FOREIGN KEY constraints.
- weakForeignKeys are rendered as plain columns with indexes but without REFERENCES.

Example run:
  python generate_sql.py \
    --schemas ../../dwc-dp/table-schemas \
    --config generate_sql.yaml \
    --output generated_from_schemas.sql
*/

-- ENUMs
CREATE TYPE degree_of_establishment AS ENUM (
  'native',
  'captive',
  'cultivated',
  'released',
  'failing',
  'casual',
  'reproducing',
  'established',
  'colonising',
  'invasive',
  'widespreadInvasive'
);

CREATE TYPE establishment_means AS ENUM (
  'native',
  'nativeReintroduced',
  'introduced',
  'introducedAssistedColonisation',
  'vagrant',
  'uncertain',
  'nativeEndemic'
);

CREATE TYPE pathway AS ENUM (
  'biologicalControl',
  'erosionControl',
  'fisheryInTheWild',
  'hunting',
  'landscapeImprovement',
  'conservationOrWildlifeManagement',
  'releasedForUse',
  'otherIntentionalRelease',
  'agriculture',
  'aquacultureMariculture',
  'publicGardenZooAquaria',
  'pet',
  'farmedAnimals',
  'forestry',
  'fur',
  'horticulture',
  'ornamentalNonHorticulture',
  'research',
  'liveFoodLiveBait',
  'otherEscape',
  'contaminantNursery',
  'contaminateBait',
  'foodContaminant',
  'contaminantOnAnimals',
  'parasitesOnAnimals',
  'contaminantOnPlants',
  'parasitesOnPlants',
  'seedContaminant',
  'timberTrade',
  'transportationHabitatMaterial',
  'fishingEquipment',
  'containerBulk',
  'hitchhikersAirplane',
  'hitchhikersShip',
  'machineryEquipment',
  'people',
  'packingMaterial',
  'ballastWater',
  'hullFouling',
  'vehicles',
  'otherTransport',
  'waterwaysBasinsSeas',
  'tunnelsBridges',
  'naturalDispersal',
  'releaseInNature',
  'escapeFromConfinement',
  'transportContaminant',
  'transportStowaway',
  'corridor',
  'unaided',
  'intentional',
  'unintentional',
  'corridorAndDispersal'
);

CREATE TYPE taxon_completeness_reported AS ENUM (
  'notReported',
  'reportedComplete',
  'reportedIncomplete'
);

CREATE TYPE event_category AS ENUM (
  'Event',
  'MaterialGathering',
  'Occurrence',
  'OrganismInteraction',
  'Survey'
);

CREATE TYPE include_or_exclude AS ENUM (
  'include',
  'exclude'
);

CREATE TYPE occurrence_status AS ENUM (
  'detected',
  'present',
  'notDetected',
  'absent'
);

CREATE TYPE relationship_targets AS ENUM (
  'Agent',
  'BibliographicResource',
  'ChronometricAge',
  'Event',
  'GeologicalContext',
  'Identification',
  'Material',
  'Media',
  'MolecularProtocol',
  'NucleotideAnalysis',
  'NucleotideSequence',
  'Occurrence',
  'Organism',
  'OrganismInteraction',
  'Protocol',
  'Provenance',
  'Survey',
  'SurveyTarget',
  'SurveyTargetDescriptor',
  'UsagePolicy'
);

-- Tables, constraints, and indexes
-- Agent
-- A resource that acts or has the power to act.
CREATE TABLE agent (
  agent_id TEXT NOT NULL PRIMARY KEY,
  agent_type TEXT,
  preferred_agent_name TEXT,
  agent_remarks TEXT
);

-- Agent Agent Role
-- A role filled by a dcterms:Agent with respect to another dcterms:Agent.
CREATE TABLE agent_agent_role (
  agent_id TEXT NOT NULL,
  related_agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE agent_agent_role ADD CONSTRAINT agent_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE agent_agent_role ADD CONSTRAINT agent_agent_role_related_agent_id_fkey FOREIGN KEY (related_agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX agent_agent_role_agent_id_idx ON agent_agent_role (agent_id);
CREATE INDEX agent_agent_role_related_agent_id_idx ON agent_agent_role (related_agent_id);

-- Agent Identifier
-- An adms:Identifier for a dcterms:Agent.
CREATE TABLE agent_identifier (
  agent_id TEXT NOT NULL,
  identifier TEXT NOT NULL,
  identifier_type TEXT,
  identifier_type_iri TEXT,
  identifier_type_source TEXT,
  identifier_language TEXT
);

ALTER TABLE agent_identifier ADD CONSTRAINT agent_identifier_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX agent_identifier_agent_id_idx ON agent_identifier (agent_id);

-- Agent Media
-- A dcterms:Agent as content in an ac:Media entity.
CREATE TABLE agent_media (
  agent_id TEXT NOT NULL,
  media_id TEXT NOT NULL,
  subject_category TEXT,
  subject_category_iri TEXT,
  subject_category_source TEXT,
  subject_part_literal TEXT,
  subject_part TEXT,
  subject_orientation_literal TEXT,
  subject_orientation TEXT,
  physical_setting TEXT
);

ALTER TABLE agent_media ADD CONSTRAINT agent_media_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE agent_media ADD CONSTRAINT agent_media_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX agent_media_agent_id_idx ON agent_media (agent_id);
CREATE INDEX agent_media_media_id_idx ON agent_media (media_id);

-- Bibliographic Resource
-- A book, article, or other documentary resource.
CREATE TABLE bibliographic_resource (
  reference_id TEXT NOT NULL PRIMARY KEY,
  is_part_of_reference_id TEXT,
  reference_type TEXT,
  bibliographic_citation TEXT,
  title TEXT,
  author TEXT,
  author_id TEXT,
  editor TEXT,
  editor_id TEXT,
  publisher TEXT,
  publisher_id TEXT,
  volume TEXT,
  issue TEXT,
  edition TEXT,
  pages TEXT,
  version TEXT,
  issued TEXT,
  accessed TEXT,
  peer_review_status BOOLEAN,
  reference_remarks TEXT
);

CREATE INDEX bibliographic_resource_is_part_of_reference_id_idx ON bibliographic_resource (is_part_of_reference_id);
CREATE INDEX bibliographic_resource_author_id_idx ON bibliographic_resource (author_id);
CREATE INDEX bibliographic_resource_editor_id_idx ON bibliographic_resource (editor_id);
CREATE INDEX bibliographic_resource_publisher_id_idx ON bibliographic_resource (publisher_id);

-- Chronometric Age
-- An approximation of temporal position (in the sense conveyed by https://www.w3.org/TR/owl-time/#time:TemporalPosition) that is supported by evidence.
CREATE TABLE chronometric_age (
  chronometric_age_id TEXT NOT NULL PRIMARY KEY,
  event_id TEXT NOT NULL,
  verbatim_chronometric_age TEXT,
  chronometric_age_protocol TEXT,
  chronometric_age_protocol_id TEXT,
  uncalibrated_chronometric_age TEXT,
  chronometric_age_conversion_protocol TEXT,
  chronometric_age_conversion_protocol_id TEXT,
  earliest_chronometric_age TEXT,
  earliest_chronometric_age_reference_system TEXT,
  latest_chronometric_age TEXT,
  latest_chronometric_age_reference_system TEXT,
  chronometric_age_uncertainty_in_years INTEGER,
  chronometric_age_uncertainty_method TEXT,
  material_dated TEXT,
  material_dated_id TEXT,
  material_dated_relationship TEXT,
  chronometric_age_determined_by TEXT,
  chronometric_age_determined_by_id TEXT,
  chronometric_age_determined_date TEXT,
  chronometric_age_references TEXT,
  chronometric_age_remarks TEXT
);

ALTER TABLE chronometric_age ADD CONSTRAINT chronometric_age_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE chronometric_age ADD CONSTRAINT chronometric_age_chronometric_age_protocol_id_fkey FOREIGN KEY (chronometric_age_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE chronometric_age ADD CONSTRAINT chronometric_age_chronometric_age_conversion_protocol_id_fkey FOREIGN KEY (chronometric_age_conversion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX chronometric_age_event_id_idx ON chronometric_age (event_id);
CREATE INDEX chronometric_age_chronometric_age_protocol_id_idx ON chronometric_age (chronometric_age_protocol_id);
CREATE INDEX chronometric_age_chronometric_age_conversion_protocol_id_idx ON chronometric_age (chronometric_age_conversion_protocol_id);
CREATE INDEX chronometric_age_material_dated_id_idx ON chronometric_age (material_dated_id);
CREATE INDEX chronometric_age_chronometric_age_determined_by_id_idx ON chronometric_age (chronometric_age_determined_by_id);

-- Chronometric Age Agent Role
-- A role filled by a dcterms:Agent with respect to a chrono:ChronometricAge.
CREATE TABLE chronometric_age_agent_role (
  chronometric_age_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE chronometric_age_agent_role ADD CONSTRAINT chronometric_age_agent_role_chronometric_age_id_fkey FOREIGN KEY (chronometric_age_id) REFERENCES chronometric_age (chronometric_age_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE chronometric_age_agent_role ADD CONSTRAINT chronometric_age_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX chronometric_age_agent_role_chronometric_age_id_idx ON chronometric_age_agent_role (chronometric_age_id);
CREATE INDEX chronometric_age_agent_role_agent_id_idx ON chronometric_age_agent_role (agent_id);

-- Chronometric Age Assertion
-- A dwc:Assertion made by a dcterms:Agent about a chrono:ChronometricAge.
CREATE TABLE chronometric_age_assertion (
  chronometric_age_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE chronometric_age_assertion ADD CONSTRAINT chronometric_age_assertion_chronometric_age_id_fkey FOREIGN KEY (chronometric_age_id) REFERENCES chronometric_age (chronometric_age_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE chronometric_age_assertion ADD CONSTRAINT chronometric_age_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX chronometric_age_assertion_chronometric_age_id_idx ON chronometric_age_assertion (chronometric_age_id);
CREATE INDEX chronometric_age_assertion_assertion_protocol_id_idx ON chronometric_age_assertion (assertion_protocol_id);
CREATE INDEX chronometric_age_assertion_assertion_by_id_idx ON chronometric_age_assertion (assertion_by_id);

-- Chronometric Age Media
-- A chrono:ChronometricAge as content in an ac:Media entity.
CREATE TABLE chronometric_age_media (
  chronometric_age_id TEXT NOT NULL,
  media_id TEXT NOT NULL,
  subject_category TEXT,
  subject_category_iri TEXT,
  subject_category_source TEXT,
  subject_part_literal TEXT,
  subject_part TEXT,
  subject_orientation_literal TEXT,
  subject_orientation TEXT,
  physical_setting TEXT
);

ALTER TABLE chronometric_age_media ADD CONSTRAINT chronometric_age_media_chronometric_age_id_fkey FOREIGN KEY (chronometric_age_id) REFERENCES chronometric_age (chronometric_age_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE chronometric_age_media ADD CONSTRAINT chronometric_age_media_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX chronometric_age_media_chronometric_age_id_idx ON chronometric_age_media (chronometric_age_id);
CREATE INDEX chronometric_age_media_media_id_idx ON chronometric_age_media (media_id);

-- Chronometric Age Protocol
-- A dwc:Protocol used for a chrono:ChronometricAge.
CREATE TABLE chronometric_age_protocol (
  chronometric_age_id TEXT NOT NULL,
  protocol_id TEXT NOT NULL
);

ALTER TABLE chronometric_age_protocol ADD CONSTRAINT chronometric_age_protocol_chronometric_age_id_fkey FOREIGN KEY (chronometric_age_id) REFERENCES chronometric_age (chronometric_age_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE chronometric_age_protocol ADD CONSTRAINT chronometric_age_protocol_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX chronometric_age_protocol_chronometric_age_id_idx ON chronometric_age_protocol (chronometric_age_id);
CREATE INDEX chronometric_age_protocol_protocol_id_idx ON chronometric_age_protocol (protocol_id);

-- Chronometric Age Reference
-- A dcterms:BibliographicResource related to a chrono:ChronometricAge.
CREATE TABLE chronometric_age_reference (
  chronometric_age_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE chronometric_age_reference ADD CONSTRAINT chronometric_age_reference_chronometric_age_id_fkey FOREIGN KEY (chronometric_age_id) REFERENCES chronometric_age (chronometric_age_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX chronometric_age_reference_chronometric_age_id_idx ON chronometric_age_reference (chronometric_age_id);
CREATE INDEX chronometric_age_reference_reference_id_idx ON chronometric_age_reference (reference_id);

-- Event
-- An action, process, or set of circumstances occurring at a dcterms:Location during a period of time.
CREATE TABLE event (
  event_id TEXT NOT NULL PRIMARY KEY,
  parent_event_id TEXT,
  preferred_event_name TEXT,
  event_category TEXT NOT NULL,
  event_type TEXT,
  dataset_name TEXT,
  dataset_id TEXT,
  field_number TEXT,
  event_conducted_by TEXT,
  event_conducted_by_id TEXT,
  event_date TEXT,
  event_time TEXT,
  start_day_of_year SMALLINT CHECK (value >= 1) CHECK (value <= 366),
  end_day_of_year SMALLINT CHECK (value >= 1) CHECK (value <= 366),
  year SMALLINT,
  month SMALLINT CHECK (value >= 1) CHECK (value <= 12),
  day SMALLINT CHECK (value >= 1) CHECK (value <= 31),
  verbatim_event_date TEXT,
  verbatim_locality TEXT,
  verbatim_elevation TEXT,
  verbatim_depth TEXT,
  verbatim_coordinates TEXT,
  verbatim_latitude TEXT,
  verbatim_longitude TEXT,
  verbatim_coordinate_system TEXT,
  verbatim_srs TEXT,
  georeference_verification_status TEXT,
  habitat TEXT,
  event_effort TEXT,
  field_notes TEXT,
  event_references TEXT,
  event_remarks TEXT,
  location_id TEXT,
  higher_geography_id TEXT,
  higher_geography TEXT,
  continent TEXT,
  water_body TEXT,
  island_group TEXT,
  island TEXT,
  country TEXT,
  country_code TEXT,
  state_province TEXT,
  county TEXT,
  municipality TEXT,
  locality TEXT,
  site_number TEXT,
  minimum_elevation_in_meters NUMERIC,
  maximum_elevation_in_meters NUMERIC,
  vertical_datum TEXT,
  minimum_depth_in_meters NUMERIC CHECK (value >= 0) CHECK (value <= 11000),
  maximum_depth_in_meters NUMERIC CHECK (value >= 0) CHECK (value <= 11000),
  minimum_distance_above_surface_in_meters NUMERIC,
  maximum_distance_above_surface_in_meters NUMERIC,
  location_remarks TEXT,
  decimal_latitude NUMERIC CHECK (value >= -90) CHECK (value <= 90),
  decimal_longitude NUMERIC CHECK (value >= -180) CHECK (value <= 180),
  geodetic_datum TEXT,
  coordinate_uncertainty_in_meters NUMERIC CHECK (value >= 1) CHECK (value <= 20037509),
  coordinate_precision NUMERIC,
  point_radius_spatial_fit NUMERIC CHECK (value >= 0),
  footprint_wkt TEXT,
  footprint_srs TEXT,
  footprint_spatial_fit NUMERIC,
  georeferenced_by TEXT,
  georeferenced_by_id TEXT,
  georeferenced_date TEXT,
  georeference_protocol TEXT,
  georeference_protocol_id TEXT,
  georeference_sources TEXT,
  georeference_remarks TEXT,
  preferred_spatial_representation TEXT,
  geological_context_id TEXT,
  feedback_url TEXT,
  information_withheld TEXT,
  data_generalizations TEXT,
  protocol_id TEXT,
  provenance_id TEXT
);

ALTER TABLE event ADD CONSTRAINT event_parent_event_id_fkey FOREIGN KEY (parent_event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE event ADD CONSTRAINT event_georeference_protocol_id_fkey FOREIGN KEY (georeference_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE event ADD CONSTRAINT event_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE event ADD CONSTRAINT event_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES provenance (provenance_id) ON DELETE CASCADE DEFERRABLE;

ALTER TABLE event ADD CONSTRAINT event_event_start_day_of_year_valid CHECK (start_day_of_year BETWEEN 1 AND 366);
ALTER TABLE event ADD CONSTRAINT event_event_end_day_of_year_valid CHECK (end_day_of_year BETWEEN 1 AND 366);
ALTER TABLE event ADD CONSTRAINT event_event_coordinate_uncertainty_in_meters_valid CHECK (coordinate_uncertainty_in_meters > 0 AND coordinate_uncertainty_in_meters <= 20037509);
ALTER TABLE event ADD CONSTRAINT event_event_coordinate_precision_valid CHECK (coordinate_precision >= 0 AND coordinate_precision <= 90);
ALTER TABLE event ADD CONSTRAINT event_event_footprint_spatial_fit_valid CHECK (footprint_spatial_fit >= 0);
ALTER TABLE event ADD CONSTRAINT event_event_point_radius_spatial_fit_valid CHECK (point_radius_spatial_fit = 0 OR point_radius_spatial_fit >= 1);

CREATE INDEX event_parent_event_id_idx ON event (parent_event_id);
CREATE INDEX event_georeference_protocol_id_idx ON event (georeference_protocol_id);
CREATE INDEX event_protocol_id_idx ON event (protocol_id);
CREATE INDEX event_provenance_id_idx ON event (provenance_id);
CREATE INDEX event_event_conducted_by_id_idx ON event (event_conducted_by_id);
CREATE INDEX event_georeferenced_by_id_idx ON event (georeferenced_by_id);
CREATE INDEX event_geological_context_id_idx ON event (geological_context_id);

-- Event Agent Role
-- A role filled by a dcterms:Agent with respect to a dwc:Event.
CREATE TABLE event_agent_role (
  event_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE event_agent_role ADD CONSTRAINT event_agent_role_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE event_agent_role ADD CONSTRAINT event_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX event_agent_role_event_id_idx ON event_agent_role (event_id);
CREATE INDEX event_agent_role_agent_id_idx ON event_agent_role (agent_id);

-- Event Assertion
-- A dwc:Assertion made by a dcterms:Agent about a dwc:Event.
CREATE TABLE event_assertion (
  event_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE event_assertion ADD CONSTRAINT event_assertion_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE event_assertion ADD CONSTRAINT event_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX event_assertion_event_id_idx ON event_assertion (event_id);
CREATE INDEX event_assertion_assertion_protocol_id_idx ON event_assertion (assertion_protocol_id);
CREATE INDEX event_assertion_assertion_by_id_idx ON event_assertion (assertion_by_id);

-- Event Identifier
-- An adms:Identifier for a dwc:Event.
CREATE TABLE event_identifier (
  event_id TEXT NOT NULL,
  identifier TEXT NOT NULL,
  identifier_type TEXT,
  identifier_type_iri TEXT,
  identifier_type_source TEXT,
  identifier_language TEXT
);

ALTER TABLE event_identifier ADD CONSTRAINT event_identifier_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX event_identifier_event_id_idx ON event_identifier (event_id);

-- Event Media
-- A dwc:Event as content in an ac:Media entity.
CREATE TABLE event_media (
  media_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  subject_category TEXT,
  subject_category_iri TEXT,
  subject_category_source TEXT,
  subject_part_literal TEXT,
  subject_part TEXT,
  subject_orientation_literal TEXT,
  subject_orientation TEXT,
  physical_setting TEXT
);

ALTER TABLE event_media ADD CONSTRAINT event_media_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE event_media ADD CONSTRAINT event_media_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX event_media_media_id_idx ON event_media (media_id);
CREATE INDEX event_media_event_id_idx ON event_media (event_id);

-- Event Protocol
-- A dwc:Protocol used for a dwc:Event.
CREATE TABLE event_protocol (
  event_id TEXT NOT NULL,
  protocol_id TEXT NOT NULL
);

ALTER TABLE event_protocol ADD CONSTRAINT event_protocol_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE event_protocol ADD CONSTRAINT event_protocol_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX event_protocol_event_id_idx ON event_protocol (event_id);
CREATE INDEX event_protocol_protocol_id_idx ON event_protocol (protocol_id);

-- Event Provenance
-- A dwc:Provenance for a dwc:Event.
CREATE TABLE event_provenance (
  event_id TEXT NOT NULL,
  provenance_id TEXT NOT NULL
);

ALTER TABLE event_provenance ADD CONSTRAINT event_provenance_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE event_provenance ADD CONSTRAINT event_provenance_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES provenance (provenance_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX event_provenance_event_id_idx ON event_provenance (event_id);
CREATE INDEX event_provenance_provenance_id_idx ON event_provenance (provenance_id);

-- Event Reference
-- A dcterms:BibliographicResource related to a dwc:Event.
CREATE TABLE event_reference (
  event_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE event_reference ADD CONSTRAINT event_reference_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX event_reference_event_id_idx ON event_reference (event_id);
CREATE INDEX event_reference_reference_id_idx ON event_reference (reference_id);

-- Geological Context
-- A set of geological designations, such as stratigraphy, that qualifies a dcterms:Location.
CREATE TABLE geological_context (
  geological_context_id TEXT NOT NULL PRIMARY KEY,
  earliest_eon_or_lowest_eonothem TEXT,
  latest_eon_or_highest_eonothem TEXT,
  earliest_era_or_lowest_erathem TEXT,
  latest_era_or_highest_erathem TEXT,
  earliest_period_or_lowest_system TEXT,
  latest_period_or_highest_system TEXT,
  earliest_epoch_or_lowest_series TEXT,
  latest_epoch_or_highest_series TEXT,
  earliest_age_or_lowest_stage TEXT,
  latest_age_or_highest_stage TEXT,
  lowest_biostratigraphic_zone TEXT,
  highest_biostratigraphic_zone TEXT,
  lithostratigraphic_terms TEXT,
  "group" TEXT,
  formation TEXT,
  member TEXT,
  bed TEXT
);

-- Geological Context Media
-- A dwc:GeologicalContext as content in an ac:Media entity.
CREATE TABLE geological_context_media (
  geological_context_id TEXT NOT NULL,
  media_id TEXT NOT NULL,
  subject_category TEXT,
  subject_category_iri TEXT,
  subject_category_source TEXT,
  subject_part_literal TEXT,
  subject_part TEXT,
  subject_orientation_literal TEXT,
  subject_orientation TEXT,
  physical_setting TEXT
);

ALTER TABLE geological_context_media ADD CONSTRAINT geological_context_media_geological_context_id_fkey FOREIGN KEY (geological_context_id) REFERENCES geological_context (geological_context_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE geological_context_media ADD CONSTRAINT geological_context_media_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX geological_context_media_geological_context_id_idx ON geological_context_media (geological_context_id);
CREATE INDEX geological_context_media_media_id_idx ON geological_context_media (media_id);

-- Identification
-- A classification of a resource according to a classification scheme.
CREATE TABLE identification (
  identification_id TEXT NOT NULL PRIMARY KEY,
  identification_type TEXT,
  material_entity_id TEXT,
  media_id TEXT,
  nucleotide_analysis_id TEXT,
  nucleotide_sequence_id TEXT,
  occurrence_id TEXT,
  organism_id TEXT,
  verbatim_identification TEXT,
  is_accepted_identification BOOLEAN,
  taxon_formula TEXT DEFAULT 'A',
  type_status TEXT,
  type_designation_type TEXT,
  identified_by TEXT,
  identified_by_id TEXT,
  date_identified TEXT,
  identification_references TEXT,
  identification_verification_status TEXT,
  identification_remarks TEXT,
  taxon_id TEXT,
  scientific_name_id TEXT,
  geo_classification_code TEXT,
  geo_name TEXT,
  scientific_name TEXT,
  scientific_name_authorship TEXT,
  vernacular_name TEXT,
  taxon_rank TEXT,
  external_classification_source TEXT,
  kingdom TEXT,
  phylum TEXT,
  "class" TEXT,
  "order" TEXT,
  family TEXT,
  subfamily TEXT,
  genus TEXT,
  generic_name TEXT,
  subgenus TEXT,
  infrageneric_epithet TEXT,
  specific_epithet TEXT,
  infraspecific_epithet TEXT,
  cultivar_epithet TEXT,
  name_according_to TEXT,
  nomenclatural_code TEXT,
  nomenclatural_status TEXT,
  name_published_in TEXT,
  name_published_in_year TEXT,
  taxon_remarks TEXT,
  feedback_url TEXT,
  protocol_id TEXT
);

ALTER TABLE identification ADD CONSTRAINT identification_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE identification ADD CONSTRAINT identification_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE identification ADD CONSTRAINT identification_nucleotide_analysis_id_fkey FOREIGN KEY (nucleotide_analysis_id) REFERENCES nucleotide_analysis (nucleotide_analysis_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE identification ADD CONSTRAINT identification_nucleotide_sequence_id_fkey FOREIGN KEY (nucleotide_sequence_id) REFERENCES nucleotide_sequence (nucleotide_sequence_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE identification ADD CONSTRAINT identification_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES occurrence (occurrence_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE identification ADD CONSTRAINT identification_organism_id_fkey FOREIGN KEY (organism_id) REFERENCES organism (organism_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE identification ADD CONSTRAINT identification_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX identification_material_entity_id_idx ON identification (material_entity_id);
CREATE INDEX identification_media_id_idx ON identification (media_id);
CREATE INDEX identification_nucleotide_analysis_id_idx ON identification (nucleotide_analysis_id);
CREATE INDEX identification_nucleotide_sequence_id_idx ON identification (nucleotide_sequence_id);
CREATE INDEX identification_occurrence_id_idx ON identification (occurrence_id);
CREATE INDEX identification_organism_id_idx ON identification (organism_id);
CREATE INDEX identification_protocol_id_idx ON identification (protocol_id);
CREATE INDEX identification_identified_by_id_idx ON identification (identified_by_id);

-- Identification Agent Role
-- A role filled by a dcterms:Agent with respect to a dwc:Identification.
CREATE TABLE identification_agent_role (
  identification_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE identification_agent_role ADD CONSTRAINT identification_agent_role_identification_id_fkey FOREIGN KEY (identification_id) REFERENCES identification (identification_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE identification_agent_role ADD CONSTRAINT identification_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX identification_agent_role_identification_id_idx ON identification_agent_role (identification_id);
CREATE INDEX identification_agent_role_agent_id_idx ON identification_agent_role (agent_id);

-- Identification Reference
-- A dcterms:BibliographicResource related to a dwc:Identification.
CREATE TABLE identification_reference (
  identification_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE identification_reference ADD CONSTRAINT identification_reference_identification_id_fkey FOREIGN KEY (identification_id) REFERENCES identification (identification_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX identification_reference_identification_id_idx ON identification_reference (identification_id);
CREATE INDEX identification_reference_reference_id_idx ON identification_reference (reference_id);

-- Identification Taxon
-- A construct of components and positions of dwc:Taxa in a dwc:Identification.
CREATE TABLE identification_taxon (
  identification_id TEXT NOT NULL,
  taxon_sort_order SMALLINT NOT NULL CHECK (value >= 1),
  taxon_id TEXT,
  scientific_name_id TEXT,
  geo_classification_code TEXT,
  geo_name TEXT,
  scientific_name TEXT,
  scientific_name_authorship TEXT,
  vernacular_name TEXT,
  taxon_rank TEXT,
  external_classification_source TEXT,
  kingdom TEXT,
  phylum TEXT,
  "class" TEXT,
  "order" TEXT,
  family TEXT,
  subfamily TEXT,
  genus TEXT,
  generic_name TEXT,
  subgenus TEXT,
  infrageneric_epithet TEXT,
  specific_epithet TEXT,
  infraspecific_epithet TEXT,
  cultivar_epithet TEXT,
  name_according_to TEXT,
  nomenclatural_code TEXT,
  nomenclatural_status TEXT,
  name_published_in TEXT,
  name_published_in_year TEXT
);

ALTER TABLE identification_taxon ADD CONSTRAINT identification_taxon_identification_id_fkey FOREIGN KEY (identification_id) REFERENCES identification (identification_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX identification_taxon_identification_id_idx ON identification_taxon (identification_id);

-- Material
-- An entity that can be identified, exist for some period of time, and consist in whole or in part of physical matter while it exists.
CREATE TABLE material (
  material_entity_id TEXT NOT NULL PRIMARY KEY,
  digital_specimen_id TEXT,
  collection_event_id TEXT,
  material_entity_category TEXT,
  discipline TEXT,
  material_entity_type TEXT,
  institution_code TEXT,
  institution_id TEXT,
  owner_institution_code TEXT,
  owner_institution_id TEXT,
  collection_code TEXT,
  collection_id TEXT,
  catalog_number TEXT,
  other_catalog_numbers TEXT,
  collected_by TEXT,
  collected_by_id TEXT,
  object_quantity TEXT,
  object_quantity_type TEXT,
  collector_number TEXT,
  preparations TEXT,
  disposition TEXT,
  verbatim_label TEXT,
  associated_sequences TEXT,
  material_references TEXT,
  information_withheld TEXT,
  data_generalizations TEXT,
  material_entity_remarks TEXT,
  evidence_for_occurrence_id TEXT,
  derived_from_material_entity_id TEXT,
  derivation_event_id TEXT,
  is_part_of_material_entity_id TEXT,
  verbatim_identification TEXT,
  type_status TEXT,
  type_designation_type TEXT,
  typified_name TEXT,
  identified_by TEXT,
  identified_by_id TEXT,
  date_identified TEXT,
  identification_references TEXT,
  identification_verification_status TEXT,
  identification_remarks TEXT,
  taxon_id TEXT,
  scientific_name_id TEXT,
  geo_classification_code TEXT,
  geo_name TEXT,
  scientific_name TEXT,
  scientific_name_authorship TEXT,
  vernacular_name TEXT,
  taxon_rank TEXT,
  external_classification_source TEXT,
  feedback_url TEXT,
  modified TEXT,
  provenance_id TEXT,
  usage_policy_id TEXT
);

ALTER TABLE material ADD CONSTRAINT material_collection_event_id_fkey FOREIGN KEY (collection_event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material ADD CONSTRAINT material_derivation_event_id_fkey FOREIGN KEY (derivation_event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material ADD CONSTRAINT material_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES provenance (provenance_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material ADD CONSTRAINT material_usage_policy_id_fkey FOREIGN KEY (usage_policy_id) REFERENCES usage_policy (usage_policy_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_collection_event_id_idx ON material (collection_event_id);
CREATE INDEX material_derivation_event_id_idx ON material (derivation_event_id);
CREATE INDEX material_provenance_id_idx ON material (provenance_id);
CREATE INDEX material_usage_policy_id_idx ON material (usage_policy_id);
CREATE INDEX material_institution_id_idx ON material (institution_id);
CREATE INDEX material_owner_institution_id_idx ON material (owner_institution_id);
CREATE INDEX material_collected_by_id_idx ON material (collected_by_id);
CREATE INDEX material_evidence_for_occurrence_id_idx ON material (evidence_for_occurrence_id);
CREATE INDEX material_derived_from_material_entity_id_idx ON material (derived_from_material_entity_id);
CREATE INDEX material_is_part_of_material_entity_id_idx ON material (is_part_of_material_entity_id);
CREATE INDEX material_identified_by_id_idx ON material (identified_by_id);

-- Material Agent Role
-- A role filled by a dcterms:Agent with respect to a dwc:MaterialEntity.
CREATE TABLE material_agent_role (
  material_entity_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE material_agent_role ADD CONSTRAINT material_agent_role_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material_agent_role ADD CONSTRAINT material_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_agent_role_material_entity_id_idx ON material_agent_role (material_entity_id);
CREATE INDEX material_agent_role_agent_id_idx ON material_agent_role (agent_id);

-- Material Assertion
-- A dwc:Assertion made by a dcterms:Agent about a dwc:MaterialEntity.
CREATE TABLE material_assertion (
  material_entity_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE material_assertion ADD CONSTRAINT material_assertion_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material_assertion ADD CONSTRAINT material_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_assertion_material_entity_id_idx ON material_assertion (material_entity_id);
CREATE INDEX material_assertion_assertion_protocol_id_idx ON material_assertion (assertion_protocol_id);
CREATE INDEX material_assertion_assertion_by_id_idx ON material_assertion (assertion_by_id);

-- Material Geological Context
-- A dwc:GeologicalContext from which a dwc:MaterialEntify was derived.
CREATE TABLE material_geological_context (
  material_entity_id TEXT NOT NULL,
  geological_context_id TEXT NOT NULL
);

ALTER TABLE material_geological_context ADD CONSTRAINT material_geological_context_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material_geological_context ADD CONSTRAINT material_geological_context_geological_context_id_fkey FOREIGN KEY (geological_context_id) REFERENCES geological_context (geological_context_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_geological_context_material_entity_id_idx ON material_geological_context (material_entity_id);
CREATE INDEX material_geological_context_geological_context_id_idx ON material_geological_context (geological_context_id);

-- Material Identifier
-- An adms:Identifier for a dwc:MaterialEntity.
CREATE TABLE material_identifier (
  material_entity_id TEXT NOT NULL,
  identifier TEXT NOT NULL,
  identifier_type TEXT,
  identifier_type_iri TEXT,
  identifier_type_source TEXT,
  identifier_language TEXT
);

ALTER TABLE material_identifier ADD CONSTRAINT material_identifier_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_identifier_material_entity_id_idx ON material_identifier (material_entity_id);

-- Material Media
-- A dwc:MaterialEntity as content in an ac:Media entity.
CREATE TABLE material_media (
  material_entity_id TEXT NOT NULL,
  media_id TEXT NOT NULL,
  subject_category TEXT,
  subject_category_iri TEXT,
  subject_category_source TEXT,
  subject_part_literal TEXT,
  subject_part TEXT,
  subject_orientation_literal TEXT,
  subject_orientation TEXT,
  physical_setting TEXT
);

ALTER TABLE material_media ADD CONSTRAINT material_media_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material_media ADD CONSTRAINT material_media_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_media_material_entity_id_idx ON material_media (material_entity_id);
CREATE INDEX material_media_media_id_idx ON material_media (media_id);

-- Material Protocol
-- A dwc:Protocol used for a dwc:MaterialEntity.
CREATE TABLE material_protocol (
  material_entity_id TEXT NOT NULL,
  protocol_id TEXT NOT NULL
);

ALTER TABLE material_protocol ADD CONSTRAINT material_protocol_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material_protocol ADD CONSTRAINT material_protocol_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_protocol_material_entity_id_idx ON material_protocol (material_entity_id);
CREATE INDEX material_protocol_protocol_id_idx ON material_protocol (protocol_id);

-- Material Provenance
-- A dwc:Provenance for a dwc:MaterialEntity.
CREATE TABLE material_provenance (
  material_entity_id TEXT NOT NULL,
  provenance_id TEXT NOT NULL
);

ALTER TABLE material_provenance ADD CONSTRAINT material_provenance_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material_provenance ADD CONSTRAINT material_provenance_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES provenance (provenance_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_provenance_material_entity_id_idx ON material_provenance (material_entity_id);
CREATE INDEX material_provenance_provenance_id_idx ON material_provenance (provenance_id);

-- Material Reference
-- A dcterms:BibliographicResource related to a dwc:MaterialEntity.
CREATE TABLE material_reference (
  material_entity_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE material_reference ADD CONSTRAINT material_reference_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_reference_material_entity_id_idx ON material_reference (material_entity_id);
CREATE INDEX material_reference_reference_id_idx ON material_reference (reference_id);

-- Material Usage Policy
-- Rights, usage, and attribution statements applicable to a dwc:MaterialEntity.
CREATE TABLE material_usage_policy (
  material_entity_id TEXT NOT NULL,
  usage_policy_id TEXT NOT NULL
);

ALTER TABLE material_usage_policy ADD CONSTRAINT material_usage_policy_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE material_usage_policy ADD CONSTRAINT material_usage_policy_usage_policy_id_fkey FOREIGN KEY (usage_policy_id) REFERENCES usage_policy (usage_policy_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX material_usage_policy_material_entity_id_idx ON material_usage_policy (material_entity_id);
CREATE INDEX material_usage_policy_usage_policy_id_idx ON material_usage_policy (usage_policy_id);

-- Media
-- A digital or physical media resource.
CREATE TABLE media (
  media_id TEXT NOT NULL PRIMARY KEY,
  derived_from_media_id TEXT,
  is_part_of_media_id TEXT,
  media_type TEXT,
  title TEXT,
  description TEXT,
  caption TEXT,
  subtype_literal TEXT,
  subtype_iri TEXT,
  collection_code TEXT,
  collection_id TEXT,
  create_date TEXT,
  time_of_day TEXT,
  digitization_date TEXT,
  capture_device TEXT,
  frame_rate NUMERIC,
  resource_creation_technique TEXT,
  sample_rate NUMERIC,
  modified TEXT,
  language TEXT,
  language_iri TEXT,
  metadata_date TEXT,
  metadata_language_literal TEXT,
  metadata_language_iri TEXT,
  provider_managed_id TEXT,
  available TEXT,
  has_service_access_point TEXT,
  service_expectation TEXT,
  access_uri TEXT,
  format TEXT,
  format_iri TEXT,
  variant_literal TEXT,
  variant_iri TEXT,
  variant_description TEXT,
  pixel_x_dimension INTEGER CHECK (value >= 1),
  pixel_y_dimension INTEGER CHECK (value >= 1),
  hash_function TEXT,
  hash_value TEXT,
  further_information_url TEXT,
  commenter_literal TEXT,
  commenter_id TEXT,
  comments TEXT,
  rating TEXT,
  reviewer_literal TEXT,
  reviewer_id TEXT,
  reviewer_comments TEXT,
  physical_setting TEXT,
  subject_category TEXT,
  subject_category_iri TEXT,
  subject_category_source TEXT,
  tag TEXT,
  subject_part_literal TEXT,
  subject_part_iri TEXT,
  subject_orientation_literal TEXT,
  subject_orientation_iri TEXT,
  start_time NUMERIC CHECK (value >= 0),
  end_time NUMERIC CHECK (value >= 0),
  start_timestamp TEXT,
  end_timestamp TEXT,
  media_duration NUMERIC CHECK (value >= 0),
  media_speed NUMERIC,
  freq_high NUMERIC,
  freq_low NUMERIC,
  x_frac NUMERIC CHECK (value >= 0) CHECK (value <= 1),
  y_frac NUMERIC CHECK (value >= 0) CHECK (value <= 1),
  height_frac NUMERIC CHECK (value >= 0) CHECK (value <= 1),
  width_frac NUMERIC CHECK (value >= 0) CHECK (value <= 1),
  radius INTEGER CHECK (value >= 0),
  provenance_id TEXT,
  usage_policy_id TEXT
);

ALTER TABLE media ADD CONSTRAINT media_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES provenance (provenance_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE media ADD CONSTRAINT media_usage_policy_id_fkey FOREIGN KEY (usage_policy_id) REFERENCES usage_policy (usage_policy_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX media_provenance_id_idx ON media (provenance_id);
CREATE INDEX media_usage_policy_id_idx ON media (usage_policy_id);
CREATE INDEX media_derived_from_media_id_idx ON media (derived_from_media_id);
CREATE INDEX media_is_part_of_media_id_idx ON media (is_part_of_media_id);
CREATE INDEX media_commenter_id_idx ON media (commenter_id);
CREATE INDEX media_reviewer_id_idx ON media (reviewer_id);

-- Media Agent Role
-- A role filled by a dcterms:Agent with respect to an ac:Media entity.
CREATE TABLE media_agent_role (
  media_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE media_agent_role ADD CONSTRAINT media_agent_role_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE media_agent_role ADD CONSTRAINT media_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX media_agent_role_media_id_idx ON media_agent_role (media_id);
CREATE INDEX media_agent_role_agent_id_idx ON media_agent_role (agent_id);

-- Media Assertion
-- A dwc:Assertion made by a dcterms:Agent about an ac:Media entity.
CREATE TABLE media_assertion (
  media_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE media_assertion ADD CONSTRAINT media_assertion_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE media_assertion ADD CONSTRAINT media_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX media_assertion_media_id_idx ON media_assertion (media_id);
CREATE INDEX media_assertion_assertion_protocol_id_idx ON media_assertion (assertion_protocol_id);
CREATE INDEX media_assertion_assertion_by_id_idx ON media_assertion (assertion_by_id);

-- Media Identifier
-- An adms:Identifier for an ac:Media entity.
CREATE TABLE media_identifier (
  media_id TEXT NOT NULL,
  identifier TEXT NOT NULL,
  identifier_type TEXT,
  identifier_type_iri TEXT,
  identifier_type_source TEXT,
  identifier_language TEXT
);

ALTER TABLE media_identifier ADD CONSTRAINT media_identifier_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX media_identifier_media_id_idx ON media_identifier (media_id);

-- Media Provenance
-- A dwc:Provenance for an ac:Media entity.
CREATE TABLE media_provenance (
  media_id TEXT NOT NULL,
  provenance_id TEXT NOT NULL
);

ALTER TABLE media_provenance ADD CONSTRAINT media_provenance_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE media_provenance ADD CONSTRAINT media_provenance_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES provenance (provenance_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX media_provenance_media_id_idx ON media_provenance (media_id);
CREATE INDEX media_provenance_provenance_id_idx ON media_provenance (provenance_id);

-- Media Usage Policy
-- Rights, usage, and attribution statements applicable to an ac:Media entity.
CREATE TABLE media_usage_policy (
  media_id TEXT NOT NULL,
  usage_policy_id TEXT NOT NULL
);

ALTER TABLE media_usage_policy ADD CONSTRAINT media_usage_policy_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE media_usage_policy ADD CONSTRAINT media_usage_policy_usage_policy_id_fkey FOREIGN KEY (usage_policy_id) REFERENCES usage_policy (usage_policy_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX media_usage_policy_media_id_idx ON media_usage_policy (media_id);
CREATE INDEX media_usage_policy_usage_policy_id_idx ON media_usage_policy (usage_policy_id);

-- Molecular Protocol
-- A protocol used to derive and identify a dwc:NucleotideSequence from an ac:MaterialEntity.
CREATE TABLE molecular_protocol (
  molecular_protocol_id TEXT NOT NULL PRIMARY KEY,
  assay_type TEXT,
  samp_name TEXT,
  project_name TEXT,
  experimental_factor TEXT,
  samp_taxon_id TEXT,
  neg_cont_type TEXT,
  pos_cont_type TEXT,
  env_broad_scale TEXT,
  env_local_scale TEXT,
  env_medium TEXT,
  subspecf_gen_lin TEXT,
  ploidy TEXT,
  num_replicons INTEGER,
  extrachrom_elements TEXT,
  estimated_size TEXT,
  ref_biomaterial TEXT,
  source_mat_id TEXT,
  pathogenicity TEXT,
  biotic_relationship TEXT,
  specific_host TEXT,
  host_spec_range TEXT,
  host_disease_stat TEXT,
  trophic_level TEXT,
  propagation TEXT,
  encoded_traits TEXT,
  rel_to_oxygen TEXT,
  isol_growth_condt TEXT,
  samp_collec_device TEXT,
  samp_collec_method TEXT,
  samp_mat_process TEXT,
  size_frac TEXT,
  samp_size TEXT,
  samp_vol_we_dna_ext TEXT,
  source_uvig TEXT,
  virus_enrich_appr TEXT,
  nucl_acid_ext TEXT,
  nucl_acid_amp TEXT,
  lib_size INTEGER,
  lib_reads_seqd INTEGER,
  lib_layout TEXT,
  lib_vector TEXT,
  lib_screen TEXT,
  target_gene TEXT,
  target_subfragment TEXT,
  pcr_primers TEXT,
  mid TEXT,
  adapters TEXT,
  pcr_cond TEXT,
  seq_meth TEXT,
  seq_quality_check TEXT,
  chimera_check TEXT,
  tax_ident TEXT,
  assembly_qual TEXT,
  assembly_name TEXT,
  assembly_software TEXT,
  annot TEXT,
  number_contig INTEGER,
  feat_pred TEXT,
  ref_db TEXT,
  sim_search_meth TEXT,
  tax_class TEXT,
  _16s_recover TEXT,
  _16s_recover_software TEXT,
  trnas INTEGER,
  trna_ext_software TEXT,
  compl_score TEXT,
  compl_software TEXT,
  compl_appr TEXT,
  contam_score TEXT,
  contam_screen_input TEXT,
  contam_screen_param TEXT,
  decontam_software TEXT,
  sort_tech TEXT,
  single_cell_lysis_appr TEXT,
  single_cell_lysis_prot TEXT,
  wga_amp_appr TEXT,
  wga_amp_kit TEXT,
  bin_param TEXT,
  bin_software TEXT,
  reassembly_bin TEXT,
  mag_cov_software TEXT,
  vir_ident_software TEXT,
  pred_genome_type TEXT,
  pred_genome_struc TEXT,
  detec_type TEXT,
  otu_class_appr TEXT,
  otu_seq_comp_appr TEXT,
  otu_db TEXT,
  host_pred_appr TEXT,
  host_pred_est_acc TEXT,
  associated_resource TEXT,
  sop TEXT,
  pcr_primer_forward TEXT,
  pcr_primer_reverse TEXT,
  pcr_primer_name_forward TEXT,
  pcr_primer_name_reverse TEXT,
  pcr_primer_reference TEXT,
  dna_sequence TEXT,
  concentration NUMERIC,
  concentration_unit TEXT,
  method_determination_concentration_and_ratios TEXT,
  ratio_of_absorbance260_230 NUMERIC,
  ratio_of_absorbance260_280 NUMERIC,
  annealing_temp NUMERIC,
  annealing_temp_unit TEXT,
  probe_reporter TEXT,
  probe_quencher TEXT,
  amplicon_size INTEGER,
  threshold_quantification_cycle NUMERIC,
  baseline_value INTEGER,
  quantification_cycle NUMERIC,
  automatic_threshold_quantification_cycle BOOLEAN,
  automatic_baseline_value TEXT,
  contamination_assessment TEXT,
  partition_volume NUMERIC,
  partition_volume_unit TEXT,
  estimated_number_of_copies INTEGER,
  amplification_reaction_volume NUMERIC,
  amplification_reaction_volume_unit TEXT,
  pcr_analysis_software TEXT,
  experimental_variance TEXT,
  pcr_primer_lod TEXT,
  pcr_primer_loq TEXT
);

CREATE INDEX molecular_protocol_source_mat_id_idx ON molecular_protocol (source_mat_id);

-- Molecular Protocol Agent Role
-- A role filled by a dcterms:Agent with respect to a dwc:MolecularProtocol.
CREATE TABLE molecular_protocol_agent_role (
  molecular_protocol_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE molecular_protocol_agent_role ADD CONSTRAINT molecular_protocol_agent_role_molecular_protocol_id_fkey FOREIGN KEY (molecular_protocol_id) REFERENCES molecular_protocol (molecular_protocol_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE molecular_protocol_agent_role ADD CONSTRAINT molecular_protocol_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX molecular_protocol_agent_role_molecular_protocol_id_idx ON molecular_protocol_agent_role (molecular_protocol_id);
CREATE INDEX molecular_protocol_agent_role_agent_id_idx ON molecular_protocol_agent_role (agent_id);

-- Molecular Protocol Assertion
-- A dwc:Assertion made by a dcterms:Agent about a dwc:MolecularProtocol.
CREATE TABLE molecular_protocol_assertion (
  molecular_protocol_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE molecular_protocol_assertion ADD CONSTRAINT molecular_protocol_assertion_molecular_protocol_id_fkey FOREIGN KEY (molecular_protocol_id) REFERENCES molecular_protocol (molecular_protocol_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE molecular_protocol_assertion ADD CONSTRAINT molecular_protocol_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX molecular_protocol_assertion_molecular_protocol_id_idx ON molecular_protocol_assertion (molecular_protocol_id);
CREATE INDEX molecular_protocol_assertion_assertion_protocol_id_idx ON molecular_protocol_assertion (assertion_protocol_id);
CREATE INDEX molecular_protocol_assertion_assertion_by_id_idx ON molecular_protocol_assertion (assertion_by_id);

-- Molecular Protocol Reference
-- A dcterms:BibliographicResource related to a dwc:MolecularProtocol.
CREATE TABLE molecular_protocol_reference (
  molecular_protocol_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE molecular_protocol_reference ADD CONSTRAINT molecular_protocol_reference_molecular_protocol_id_fkey FOREIGN KEY (molecular_protocol_id) REFERENCES molecular_protocol (molecular_protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX molecular_protocol_reference_molecular_protocol_id_idx ON molecular_protocol_reference (molecular_protocol_id);
CREATE INDEX molecular_protocol_reference_reference_id_idx ON molecular_protocol_reference (reference_id);

-- Nucleotide Analysis
-- A link between a dwc:NucleotideSequence and a dwc:Event and a dwc:MaterialEntity from which it was derived, using a specified dwc:Protocol.
CREATE TABLE nucleotide_analysis (
  nucleotide_analysis_id TEXT NOT NULL PRIMARY KEY,
  event_id TEXT,
  molecular_protocol_id TEXT NOT NULL,
  nucleotide_sequence_id TEXT NOT NULL,
  material_entity_id TEXT,
  read_count INTEGER,
  total_read_count INTEGER
);

ALTER TABLE nucleotide_analysis ADD CONSTRAINT nucleotide_analysis_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE nucleotide_analysis ADD CONSTRAINT nucleotide_analysis_molecular_protocol_id_fkey FOREIGN KEY (molecular_protocol_id) REFERENCES molecular_protocol (molecular_protocol_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE nucleotide_analysis ADD CONSTRAINT nucleotide_analysis_nucleotide_sequence_id_fkey FOREIGN KEY (nucleotide_sequence_id) REFERENCES nucleotide_sequence (nucleotide_sequence_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE nucleotide_analysis ADD CONSTRAINT nucleotide_analysis_material_entity_id_fkey FOREIGN KEY (material_entity_id) REFERENCES material (material_entity_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX nucleotide_analysis_event_id_idx ON nucleotide_analysis (event_id);
CREATE INDEX nucleotide_analysis_molecular_protocol_id_idx ON nucleotide_analysis (molecular_protocol_id);
CREATE INDEX nucleotide_analysis_nucleotide_sequence_id_idx ON nucleotide_analysis (nucleotide_sequence_id);
CREATE INDEX nucleotide_analysis_material_entity_id_idx ON nucleotide_analysis (material_entity_id);

-- Nucleotide Analysis Assertion
-- A dwc:Assertion made by a dcterms:Agent about a dwc:NucleotideSequence.
CREATE TABLE nucleotide_analysis_assertion (
  nucleotide_analysis_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE nucleotide_analysis_assertion ADD CONSTRAINT nucleotide_analysis_assertion_nucleotide_analysis_id_fkey FOREIGN KEY (nucleotide_analysis_id) REFERENCES nucleotide_analysis (nucleotide_analysis_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE nucleotide_analysis_assertion ADD CONSTRAINT nucleotide_analysis_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX nucleotide_analysis_assertion_nucleotide_analysis_id_idx ON nucleotide_analysis_assertion (nucleotide_analysis_id);
CREATE INDEX nucleotide_analysis_assertion_assertion_protocol_id_idx ON nucleotide_analysis_assertion (assertion_protocol_id);
CREATE INDEX nucleotide_analysis_assertion_assertion_by_id_idx ON nucleotide_analysis_assertion (assertion_by_id);

-- Nucleotide Sequence
-- A digital representation of a nucleotide sequence.
CREATE TABLE nucleotide_sequence (
  nucleotide_sequence_id TEXT NOT NULL PRIMARY KEY,
  sequence TEXT,
  nucleotide_sequence_remarks TEXT
);

-- Occurrence
-- A state of a dwc:Organism in a dwc:Event.
CREATE TABLE occurrence (
  occurrence_id TEXT NOT NULL PRIMARY KEY,
  event_id TEXT NOT NULL,
  is_part_of_occurrence_id TEXT,
  survey_target_id TEXT,
  recorded_by TEXT,
  recorded_by_id TEXT,
  organism_quantity TEXT,
  organism_quantity_type TEXT,
  sex TEXT,
  life_stage TEXT,
  reproductive_condition TEXT,
  caste TEXT,
  behavior TEXT,
  vitality TEXT,
  establishment_means establishment_means,
  degree_of_establishment degree_of_establishment,
  pathway pathway,
  substrate TEXT,
  occurrence_status occurrence_status NOT NULL DEFAULT 'detected',
  occurrence_references TEXT,
  information_withheld TEXT,
  data_generalizations TEXT,
  occurrence_remarks TEXT,
  organism_id TEXT,
  organism_scope TEXT DEFAULT 'multicellular organism',
  organism_name TEXT,
  cause_of_death TEXT,
  organism_remarks TEXT,
  verbatim_identification TEXT,
  identified_by TEXT,
  identified_by_id TEXT,
  date_identified TEXT,
  identification_references TEXT,
  identification_verification_status TEXT,
  identification_remarks TEXT,
  taxon_id TEXT,
  scientific_name_id TEXT,
  scientific_name TEXT,
  scientific_name_authorship TEXT,
  vernacular_name TEXT,
  taxon_rank TEXT,
  external_classification_source TEXT,
  feedback_url TEXT,
  protocol_id TEXT
);

ALTER TABLE occurrence ADD CONSTRAINT occurrence_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE occurrence ADD CONSTRAINT occurrence_is_part_of_occurrence_id_fkey FOREIGN KEY (is_part_of_occurrence_id) REFERENCES occurrence (occurrence_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE occurrence ADD CONSTRAINT occurrence_survey_target_id_fkey FOREIGN KEY (survey_target_id) REFERENCES survey_target (survey_target_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE occurrence ADD CONSTRAINT occurrence_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX occurrence_event_id_idx ON occurrence (event_id);
CREATE INDEX occurrence_is_part_of_occurrence_id_idx ON occurrence (is_part_of_occurrence_id);
CREATE INDEX occurrence_survey_target_id_idx ON occurrence (survey_target_id);
CREATE INDEX occurrence_protocol_id_idx ON occurrence (protocol_id);
CREATE INDEX occurrence_recorded_by_id_idx ON occurrence (recorded_by_id);
CREATE INDEX occurrence_organism_id_idx ON occurrence (organism_id);
CREATE INDEX occurrence_identified_by_id_idx ON occurrence (identified_by_id);

-- Occurrence Agent Role
-- A role filled by a dcterms:Agent with respect to a dwc:Occurrence.
CREATE TABLE occurrence_agent_role (
  occurrence_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE occurrence_agent_role ADD CONSTRAINT occurrence_agent_role_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES occurrence (occurrence_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE occurrence_agent_role ADD CONSTRAINT occurrence_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX occurrence_agent_role_occurrence_id_idx ON occurrence_agent_role (occurrence_id);
CREATE INDEX occurrence_agent_role_agent_id_idx ON occurrence_agent_role (agent_id);

-- Occurrence Assertion
-- A dwc:Assertion made by a dcterms:Agent about a dwc:Occurrence.
CREATE TABLE occurrence_assertion (
  occurrence_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE occurrence_assertion ADD CONSTRAINT occurrence_assertion_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES occurrence (occurrence_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE occurrence_assertion ADD CONSTRAINT occurrence_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX occurrence_assertion_occurrence_id_idx ON occurrence_assertion (occurrence_id);
CREATE INDEX occurrence_assertion_assertion_protocol_id_idx ON occurrence_assertion (assertion_protocol_id);
CREATE INDEX occurrence_assertion_assertion_by_id_idx ON occurrence_assertion (assertion_by_id);

-- Occurrence Identifier
-- An adms:Identifier for a dwc:Occurrence.
CREATE TABLE occurrence_identifier (
  occurrence_id TEXT NOT NULL,
  identifier TEXT NOT NULL,
  identifier_type TEXT,
  identifier_type_iri TEXT,
  identifier_type_source TEXT,
  identifier_language TEXT
);

ALTER TABLE occurrence_identifier ADD CONSTRAINT occurrence_identifier_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES occurrence (occurrence_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX occurrence_identifier_occurrence_id_idx ON occurrence_identifier (occurrence_id);

-- Occurrence Media
-- A dwc:Occurrence as content in an ac:Media entity.
CREATE TABLE occurrence_media (
  occurrence_id TEXT NOT NULL,
  media_id TEXT NOT NULL,
  subject_category TEXT,
  subject_category_iri TEXT,
  subject_category_source TEXT,
  subject_part_literal TEXT,
  subject_part TEXT,
  subject_orientation_literal TEXT,
  subject_orientation TEXT,
  physical_setting TEXT
);

ALTER TABLE occurrence_media ADD CONSTRAINT occurrence_media_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES occurrence (occurrence_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE occurrence_media ADD CONSTRAINT occurrence_media_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX occurrence_media_occurrence_id_idx ON occurrence_media (occurrence_id);
CREATE INDEX occurrence_media_media_id_idx ON occurrence_media (media_id);

-- Occurrence Protocol
-- A dwc:Protocol used for a dwc:Occurrence.
CREATE TABLE occurrence_protocol (
  occurrence_id TEXT NOT NULL,
  protocol_id TEXT NOT NULL
);

ALTER TABLE occurrence_protocol ADD CONSTRAINT occurrence_protocol_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES occurrence (occurrence_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE occurrence_protocol ADD CONSTRAINT occurrence_protocol_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX occurrence_protocol_occurrence_id_idx ON occurrence_protocol (occurrence_id);
CREATE INDEX occurrence_protocol_protocol_id_idx ON occurrence_protocol (protocol_id);

-- Occurrence Reference
-- A dcterms:BibliographicResource related to a dwc:Occurrence.
CREATE TABLE occurrence_reference (
  occurrence_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE occurrence_reference ADD CONSTRAINT occurrence_reference_occurrence_id_fkey FOREIGN KEY (occurrence_id) REFERENCES occurrence (occurrence_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX occurrence_reference_occurrence_id_idx ON occurrence_reference (occurrence_id);
CREATE INDEX occurrence_reference_reference_id_idx ON occurrence_reference (reference_id);

-- Organism
-- A particular organism or defined group of organisms considered to be taxonomically homogeneous.
CREATE TABLE organism (
  organism_id TEXT NOT NULL PRIMARY KEY,
  organism_scope TEXT,
  organism_name TEXT,
  cause_of_death TEXT,
  associated_organisms TEXT,
  organism_remarks TEXT
);

-- Organism Assertion
-- A dwc:Assertion made by a dcterms:Agent about a dwc:Organism.
CREATE TABLE organism_assertion (
  organism_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE organism_assertion ADD CONSTRAINT organism_assertion_organism_id_fkey FOREIGN KEY (organism_id) REFERENCES organism (organism_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE organism_assertion ADD CONSTRAINT organism_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX organism_assertion_organism_id_idx ON organism_assertion (organism_id);
CREATE INDEX organism_assertion_assertion_protocol_id_idx ON organism_assertion (assertion_protocol_id);
CREATE INDEX organism_assertion_assertion_by_id_idx ON organism_assertion (assertion_by_id);

-- Organism Identifier
-- An adms:Identifier for a dwc:Organism.
CREATE TABLE organism_identifier (
  organism_id TEXT NOT NULL,
  identifier TEXT NOT NULL,
  identifier_type TEXT,
  identifier_type_iri TEXT,
  identifier_type_source TEXT,
  identifier_language TEXT
);

ALTER TABLE organism_identifier ADD CONSTRAINT organism_identifier_organism_id_fkey FOREIGN KEY (organism_id) REFERENCES organism (organism_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX organism_identifier_organism_id_idx ON organism_identifier (organism_id);

-- Organism Interaction
-- An interaction between two dwc:Organisms during a dwc:Event.
CREATE TABLE organism_interaction (
  organism_interaction_id TEXT NOT NULL PRIMARY KEY,
  event_id TEXT NOT NULL,
  organism_interaction_description TEXT,
  subject_occurrence_id TEXT NOT NULL,
  subject_organism_part TEXT,
  organism_interaction_type TEXT,
  related_occurrence_id TEXT,
  external_related_occurrence_id TEXT,
  external_related_occurrence_source TEXT,
  related_organism_part TEXT,
  feedback_url TEXT
);

ALTER TABLE organism_interaction ADD CONSTRAINT organism_interaction_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE organism_interaction ADD CONSTRAINT organism_interaction_subject_occurrence_id_fkey FOREIGN KEY (subject_occurrence_id) REFERENCES occurrence (occurrence_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX organism_interaction_event_id_idx ON organism_interaction (event_id);
CREATE INDEX organism_interaction_subject_occurrence_id_idx ON organism_interaction (subject_occurrence_id);
CREATE INDEX organism_interaction_related_occurrence_id_idx ON organism_interaction (related_occurrence_id);

-- Organism Interaction Agent Role
-- A role filled by a dcterms:Agent with respect to a dwc:OrganismInteraction.
CREATE TABLE organism_interaction_agent_role (
  organism_interaction_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE organism_interaction_agent_role ADD CONSTRAINT organism_interaction_agent_role_organism_interaction_id_fkey FOREIGN KEY (organism_interaction_id) REFERENCES organism_interaction (organism_interaction_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE organism_interaction_agent_role ADD CONSTRAINT organism_interaction_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX organism_interaction_agent_role_organism_interaction_id_idx ON organism_interaction_agent_role (organism_interaction_id);
CREATE INDEX organism_interaction_agent_role_agent_id_idx ON organism_interaction_agent_role (agent_id);

-- Organism Interaction Assertion
-- A dwc:Assertion made by a dcterms:Agent about a dwc:OrganismInteraction.
CREATE TABLE organism_interaction_assertion (
  organism_interaction_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE organism_interaction_assertion ADD CONSTRAINT organism_interaction_assertion_organism_interaction_id_fkey FOREIGN KEY (organism_interaction_id) REFERENCES organism_interaction (organism_interaction_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE organism_interaction_assertion ADD CONSTRAINT organism_interaction_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX organism_interaction_assertion_organism_interaction_id_idx ON organism_interaction_assertion (organism_interaction_id);
CREATE INDEX organism_interaction_assertion_assertion_protocol_id_idx ON organism_interaction_assertion (assertion_protocol_id);
CREATE INDEX organism_interaction_assertion_assertion_by_id_idx ON organism_interaction_assertion (assertion_by_id);

-- Organism Interaction Media
-- A dwc:OrganismInteraction as content in an ac:Media entity.
CREATE TABLE organism_interaction_media (
  organism_interaction_id TEXT NOT NULL,
  media_id TEXT NOT NULL,
  subject_category TEXT,
  subject_category_iri TEXT,
  subject_category_source TEXT,
  subject_part_literal TEXT,
  subject_part TEXT,
  subject_orientation_literal TEXT,
  subject_orientation TEXT,
  physical_setting TEXT
);

ALTER TABLE organism_interaction_media ADD CONSTRAINT organism_interaction_media_organism_interaction_id_fkey FOREIGN KEY (organism_interaction_id) REFERENCES organism_interaction (organism_interaction_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE organism_interaction_media ADD CONSTRAINT organism_interaction_media_media_id_fkey FOREIGN KEY (media_id) REFERENCES media (media_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX organism_interaction_media_organism_interaction_id_idx ON organism_interaction_media (organism_interaction_id);
CREATE INDEX organism_interaction_media_media_id_idx ON organism_interaction_media (media_id);

-- Organism Interaction Reference
-- A dcterms:BibliographicResource related to a dwc:OrganismInteraction.
CREATE TABLE organism_interaction_reference (
  organism_interaction_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE organism_interaction_reference ADD CONSTRAINT organism_interaction_reference_organism_interaction_id_fkey FOREIGN KEY (organism_interaction_id) REFERENCES organism_interaction (organism_interaction_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX organism_interaction_reference_organism_interaction_id_idx ON organism_interaction_reference (organism_interaction_id);
CREATE INDEX organism_interaction_reference_reference_id_idx ON organism_interaction_reference (reference_id);

-- Organism Reference
-- A dcterms:BibliographicResource related to a dwc:Organism.
CREATE TABLE organism_reference (
  organism_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE organism_reference ADD CONSTRAINT organism_reference_organism_id_fkey FOREIGN KEY (organism_id) REFERENCES organism (organism_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX organism_reference_organism_id_idx ON organism_reference (organism_id);
CREATE INDEX organism_reference_reference_id_idx ON organism_reference (reference_id);

-- Organism Relationship
-- A dwc:ResourceRelationship of one dwc:Organism to another dwc:Organism.
CREATE TABLE organism_relationship (
  organism_relationship_id TEXT NOT NULL PRIMARY KEY,
  subject_organism_id TEXT NOT NULL,
  relationship_type TEXT,
  relationship_type_iri TEXT,
  relationship_type_source TEXT,
  related_organism_id TEXT,
  external_related_organism_id TEXT,
  external_related_organism_source TEXT,
  relationship_order INTEGER CHECK (value >= 1),
  relationship_according_to TEXT,
  relationship_according_to_id TEXT,
  relationship_established_date TEXT,
  relationship_remarks TEXT
);

ALTER TABLE organism_relationship ADD CONSTRAINT organism_relationship_subject_organism_id_fkey FOREIGN KEY (subject_organism_id) REFERENCES organism (organism_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX organism_relationship_subject_organism_id_idx ON organism_relationship (subject_organism_id);
CREATE INDEX organism_relationship_related_organism_id_idx ON organism_relationship (related_organism_id);
CREATE INDEX organism_relationship_relationship_according_to_id_idx ON organism_relationship (relationship_according_to_id);

-- Protocol
-- A method used during an action.
CREATE TABLE protocol (
  protocol_id TEXT NOT NULL PRIMARY KEY,
  protocol_type TEXT,
  protocol_name TEXT,
  protocol_description TEXT,
  protocol_references TEXT,
  protocol_remarks TEXT
);

-- Protocol Reference
-- A dcterms:BibliographicResource related to a dwc:Protocol.
CREATE TABLE protocol_reference (
  protocol_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE protocol_reference ADD CONSTRAINT protocol_reference_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX protocol_reference_protocol_id_idx ON protocol_reference (protocol_id);
CREATE INDEX protocol_reference_reference_id_idx ON protocol_reference (reference_id);

-- Provenance
-- Information about an entity’s origins.
CREATE TABLE provenance (
  provenance_id TEXT NOT NULL PRIMARY KEY,
  dataset_id TEXT,
  funding_attribution TEXT,
  funding_attribution_id TEXT,
  source TEXT,
  source_iri TEXT,
  creator_literal TEXT,
  creator_id TEXT,
  provider_literal TEXT,
  provider_id TEXT,
  metadata_creator_literal TEXT,
  metadata_creator_id TEXT,
  metadata_provider_literal TEXT,
  metadata_provider_id TEXT,
  further_information_url TEXT,
  feedback_url TEXT,
  "references" TEXT,
  bibliographic_citation TEXT,
  project_id TEXT,
  project_title TEXT
);

CREATE INDEX provenance_funding_attribution_id_idx ON provenance (funding_attribution_id);
CREATE INDEX provenance_creator_id_idx ON provenance (creator_id);
CREATE INDEX provenance_provider_id_idx ON provenance (provider_id);
CREATE INDEX provenance_metadata_creator_id_idx ON provenance (metadata_creator_id);
CREATE INDEX provenance_metadata_provider_id_idx ON provenance (metadata_provider_id);

-- Resource Relationship
-- A relationship of one rdfs:Resource (http://www.w3.org/2000/01/rdf-schema#Resource) to another.
CREATE TABLE resource_relationship (
  resource_relationship_id TEXT NOT NULL PRIMARY KEY,
  subject_resource_id TEXT NOT NULL,
  subject_resource_type relationship_targets,
  subject_resource_type_iri TEXT,
  subject_resource_type_source TEXT,
  relationship_type TEXT,
  relationship_type_iri TEXT,
  relationship_type_source TEXT,
  related_resource_id TEXT,
  external_related_resource_id TEXT,
  external_related_resource_source TEXT,
  related_resource_type relationship_targets,
  related_resource_type_iri TEXT,
  related_resource_type_source TEXT,
  relationship_order SMALLINT DEFAULT 1 CHECK (value >= 1),
  relationship_according_to TEXT,
  relationship_according_to_id TEXT,
  relationship_established_date TEXT,
  relationship_remarks TEXT
);

-- Survey
-- A biotic survey or inventory.
CREATE TABLE survey (
  survey_id TEXT NOT NULL PRIMARY KEY,
  event_id TEXT NOT NULL,
  site_count SMALLINT CHECK (value >= 1),
  site_nesting_description TEXT,
  verbatim_site_descriptions TEXT,
  verbatim_site_names TEXT,
  geospatial_scope_area_value NUMERIC CHECK (value >= 0),
  geospatial_scope_area_unit TEXT,
  total_area_sampled_unit TEXT,
  total_area_sampled_value NUMERIC CHECK (value >= 0),
  reported_extreme_conditions TEXT,
  reported_weather TEXT,
  event_duration_value NUMERIC CHECK (value >= 0),
  event_duration_unit TEXT,
  taxon_completeness_reported taxon_completeness_reported DEFAULT 'notReported',
  taxon_completeness_protocols TEXT,
  is_absence_reported BOOLEAN,
  absent_taxa TEXT,
  has_non_target_taxa BOOLEAN,
  non_target_taxa TEXT,
  are_non_target_taxa_fully_reported BOOLEAN,
  has_non_target_organisms BOOLEAN,
  verbatim_target_scope TEXT,
  identified_by TEXT,
  identified_by_id TEXT,
  identification_references TEXT,
  compilation_types TEXT,
  compilation_source_types TEXT,
  inventory_types TEXT,
  protocol_names TEXT,
  protocol_descriptions TEXT,
  protocol_references TEXT,
  is_abundance_reported BOOLEAN,
  is_abundance_cap_reported BOOLEAN,
  abundance_cap SMALLINT CHECK (value >= 0),
  is_vegetation_cover_reported BOOLEAN,
  is_least_specific_target_category_quantity_inclusive BOOLEAN,
  has_vouchers BOOLEAN,
  voucher_institutions TEXT,
  has_material_samples BOOLEAN,
  material_sample_types TEXT,
  sampling_protocol TEXT,
  sampling_protocol_id TEXT,
  sample_size_value TEXT,
  sample_size_unit TEXT,
  sampling_performed_by TEXT,
  sampling_performed_by_id TEXT,
  is_sampling_effort_reported BOOLEAN,
  sampling_effort_protocol TEXT,
  sampling_effort_protocol_id TEXT,
  sampling_effort_value NUMERIC CHECK (value >= 0),
  sampling_effort_unit TEXT,
  information_withheld TEXT,
  data_generalizations TEXT,
  feedback_url TEXT
);

ALTER TABLE survey ADD CONSTRAINT survey_event_id_fkey FOREIGN KEY (event_id) REFERENCES event (event_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE survey ADD CONSTRAINT survey_sampling_effort_protocol_id_fkey FOREIGN KEY (sampling_effort_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX survey_event_id_idx ON survey (event_id);
CREATE INDEX survey_sampling_effort_protocol_id_idx ON survey (sampling_effort_protocol_id);
CREATE INDEX survey_identified_by_id_idx ON survey (identified_by_id);
CREATE INDEX survey_sampling_protocol_id_idx ON survey (sampling_protocol_id);
CREATE INDEX survey_sampling_performed_by_id_idx ON survey (sampling_performed_by_id);

-- Survey Agent Role
-- A role filled by a dcterms:Agent with respect to an eco:Survey.
CREATE TABLE survey_agent_role (
  survey_id TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  agent_role TEXT,
  agent_role_iri TEXT,
  agent_role_source TEXT,
  agent_role_order SMALLINT NOT NULL DEFAULT 1 CHECK (value >= 1),
  agent_role_date TEXT
);

ALTER TABLE survey_agent_role ADD CONSTRAINT survey_agent_role_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES survey (survey_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE survey_agent_role ADD CONSTRAINT survey_agent_role_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agent (agent_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX survey_agent_role_survey_id_idx ON survey_agent_role (survey_id);
CREATE INDEX survey_agent_role_agent_id_idx ON survey_agent_role (agent_id);

-- Survey Assertion
-- A dwc:Assertion made by a dcterms:Agent about an eco:Survey.
CREATE TABLE survey_assertion (
  survey_id TEXT NOT NULL,
  assertion_id TEXT UNIQUE,
  verbatim_assertion_type TEXT,
  assertion_type TEXT,
  assertion_type_iri TEXT,
  assertion_type_source TEXT,
  assertion_made_date TEXT,
  assertion_effective_date TEXT,
  assertion_value TEXT,
  assertion_value_iri TEXT,
  assertion_value_source TEXT,
  assertion_unit TEXT,
  assertion_unit_iri TEXT,
  assertion_unit_source TEXT,
  assertion_error TEXT,
  assertion_by TEXT,
  assertion_by_id TEXT,
  assertion_protocols TEXT,
  assertion_protocol_id TEXT,
  assertion_references TEXT,
  assertion_remarks TEXT
);

ALTER TABLE survey_assertion ADD CONSTRAINT survey_assertion_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES survey (survey_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE survey_assertion ADD CONSTRAINT survey_assertion_assertion_protocol_id_fkey FOREIGN KEY (assertion_protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX survey_assertion_survey_id_idx ON survey_assertion (survey_id);
CREATE INDEX survey_assertion_assertion_protocol_id_idx ON survey_assertion (assertion_protocol_id);
CREATE INDEX survey_assertion_assertion_by_id_idx ON survey_assertion (assertion_by_id);

-- Survey Identifier
-- An adms:Identifier for an eco:Survey.
CREATE TABLE survey_identifier (
  survey_id TEXT NOT NULL,
  identifier TEXT NOT NULL,
  identifier_type TEXT,
  identifier_type_iri TEXT,
  identifier_type_source TEXT,
  identifier_language TEXT
);

ALTER TABLE survey_identifier ADD CONSTRAINT survey_identifier_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES survey (survey_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX survey_identifier_survey_id_idx ON survey_identifier (survey_id);

-- Survey Protocol
-- A dwc:Protocol used for an eco:Survey.
CREATE TABLE survey_protocol (
  survey_id TEXT NOT NULL,
  protocol_id TEXT NOT NULL
);

ALTER TABLE survey_protocol ADD CONSTRAINT survey_protocol_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES survey (survey_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE survey_protocol ADD CONSTRAINT survey_protocol_protocol_id_fkey FOREIGN KEY (protocol_id) REFERENCES protocol (protocol_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX survey_protocol_survey_id_idx ON survey_protocol (survey_id);
CREATE INDEX survey_protocol_protocol_id_idx ON survey_protocol (protocol_id);

-- Survey Reference
-- A dcterms:BibliographicResource related to an eco:Survey.
CREATE TABLE survey_reference (
  survey_id TEXT NOT NULL,
  reference_id TEXT NOT NULL,
  relationship_type TEXT
);

ALTER TABLE survey_reference ADD CONSTRAINT survey_reference_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES survey (survey_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX survey_reference_survey_id_idx ON survey_reference (survey_id);
CREATE INDEX survey_reference_reference_id_idx ON survey_reference (reference_id);

-- Survey Survey Target
-- An eco:SurveyTarget used for an eco:Survey.
CREATE TABLE survey_survey_target (
  survey_id TEXT NOT NULL,
  survey_target_id TEXT NOT NULL
);

ALTER TABLE survey_survey_target ADD CONSTRAINT survey_survey_target_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES survey (survey_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE survey_survey_target ADD CONSTRAINT survey_survey_target_survey_target_id_fkey FOREIGN KEY (survey_target_id) REFERENCES survey_target (survey_target_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX survey_survey_target_survey_id_idx ON survey_survey_target (survey_id);
CREATE INDEX survey_survey_target_survey_target_id_idx ON survey_survey_target (survey_target_id);

-- Survey Target
-- An intended scope for dwc:Occurrences in an eco:Survey.
CREATE TABLE survey_target (
  survey_target_id TEXT NOT NULL PRIMARY KEY,
  survey_target_description TEXT,
  is_survey_target_fully_reported BOOLEAN NOT NULL,
  survey_target_remarks TEXT
);

-- Survey Target Descriptor
-- A combination of a survey target value and a survey target type for given eco:SurveyTarget.
CREATE TABLE survey_target_descriptor (
  survey_target_id TEXT NOT NULL,
  survey_target_type TEXT,
  survey_target_type_iri TEXT,
  survey_target_type_source TEXT,
  survey_target_value TEXT,
  survey_target_value_iri TEXT,
  survey_target_value_source TEXT,
  survey_target_unit TEXT,
  survey_target_unit_iri TEXT,
  survey_target_unit_source TEXT,
  include_or_exclude include_or_exclude NOT NULL DEFAULT 'include'
);

ALTER TABLE survey_target_descriptor ADD CONSTRAINT survey_target_descriptor_survey_target_id_fkey FOREIGN KEY (survey_target_id) REFERENCES survey_target (survey_target_id) ON DELETE CASCADE DEFERRABLE;

CREATE INDEX survey_target_descriptor_survey_target_id_idx ON survey_target_descriptor (survey_target_id);

-- Usage Policy
-- Information about rights, usage, and attribution statements applicable to an entity.
CREATE TABLE usage_policy (
  usage_policy_id TEXT NOT NULL PRIMARY KEY,
  rights TEXT,
  rights_iri TEXT,
  rights_holder TEXT,
  rights_holder_id TEXT,
  owner TEXT,
  owner_id TEXT,
  usage_terms TEXT,
  web_statement TEXT,
  access_rights TEXT,
  license TEXT,
  license_logo_url TEXT,
  licensing_exception TEXT,
  credit TEXT,
  attribution_logo_url TEXT,
  attribution_link_url TEXT
);

CREATE INDEX usage_policy_rights_holder_id_idx ON usage_policy (rights_holder_id);
CREATE INDEX usage_policy_owner_id_idx ON usage_policy (owner_id);
